-- MySQL Script generated by MySQL Workbench
-- 02/28/16 17:17:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CrapStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CrapStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CrapStore` DEFAULT CHARACTER SET utf8 ;
USE `CrapStore` ;

-- -----------------------------------------------------
-- Table `CrapStore`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CrapStore`.`User` ;

CREATE TABLE IF NOT EXISTS `CrapStore`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `isSupplier` TINYINT(1) NOT NULL DEFAULT 0,
  `hint` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CrapStore`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CrapStore`.`Product` ;

CREATE TABLE IF NOT EXISTS `CrapStore`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `qty` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(2000) NOT NULL,
  `price` FLOAT NOT NULL,
  `hidden` TINYINT(1) NOT NULL DEFAULT 0,
  `idSupplier` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `Supplier_idx` (`idSupplier` ASC),
  CONSTRAINT `Supplier`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `CrapStore`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CrapStore`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CrapStore`.`Order` ;

CREATE TABLE IF NOT EXISTS `CrapStore`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`idOrder`),
  INDEX `Order_User_idx` (`User_id` ASC),
  CONSTRAINT `Order_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `CrapStore`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CrapStore`.`OrderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CrapStore`.`OrderItem` ;

CREATE TABLE IF NOT EXISTS `CrapStore`.`OrderItem` (
  `idOrder` INT NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idProduct`),
  INDEX `idProductt_idx` (`idProduct` ASC),
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `CrapStore`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `CrapStore`.`Product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CrapStore`.`GuestBookEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CrapStore`.`GuestBookEntry` ;

CREATE TABLE IF NOT EXISTS `CrapStore`.`GuestBookEntry` (
  `idGuestBookEntry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(255) NULL,
  `message` VARCHAR(500) NULL,
  PRIMARY KEY (`idGuestBookEntry`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
